config/routes.rb
Rails.application.routes.draw do
	resources :games
	resources :players

	root :to => 'home#index'

	get 'players/:username', to: 'players#show'

	post 'loguser', to: 'authentication#logUser', as: :login
	get 'login', to: 'authentication#logIn'

end

app/models/game.rb
class Game < ActiveResource::Base
	self.site = "http://127.0.0.1:3023"
end

app/models/player.rb
class Player < ActiveResource::Base
	self.site = "http://127.0.0.1:3023"
	self.format = :json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def logIn
  end

  def logUser
  	@player = JSON.parse Player.post(:login, {},params[:player].to_json).body
  	logger.debug @player["username"]
  	redirect_to player_url(@player, :id => @player["username"])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  	@game = Game.build
  end

  def create
  	Game.new(params[:game]).save();
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
  	@player = Player.build
  end

  def create
  	Player.new(params[:player]).save();
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authentication/logIn.html.erb
<h1>Log in</h1>
<%= form_for(:player, url: login_path) do |player|  %>
	<%= player.label :username %>
    <%= player.text_field  :username %><br />
    <%= player.label :password %>
    <%= player.text_field  :password %><br />

    <%= player.submit "Register", class: "btn btn-primary" %>
 <%end%>

app/views/games/new.html.erb
<h1>Create your own game</h1>
<%= form_for @game, :url => { :action => "create" }  do |game|  %>
	<%= game.label :name %>
    <%= game.text_field  :name %><br />
    <% @game.actions.each_with_index do |action, index| %>
    	<%= game.fields_for "actions[]", action do |action_fields| %>
          <%= action_fields.text_field :text%>
          <%= action_fields.select :points, (1..10) %>
        <% end %>
    <% end %>

    <%= game.submit "Add game", class: "btn btn-primary" %>
 <%end%>

app/views/home/index.html.erb
<h1>Gamification's Home</h1>
<p>
	<%= button_to("Sign up!", {controller: "players", action: "new"}, method: "get") %>

	<%= button_to("Log In", "/login", method: "get") %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamificationSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/new.html.erb
<h1>Sign up</h1>
<%= form_for @player, :url => { :action => "create" }  do |player|  %>
	<%= player.label :username %>
    <%= player.text_field  :username %><br />
    <%= player.label :password %>
    <%= player.text_field  :password %><br />
    <%= player.label :email %>
    <%= player.text_field  :email %><br />

    <%= player.submit "Register", class: "btn btn-primary" %>
 <%end%>

app/views/players/show.html.erb
<%= @player.username %>